# Steps in conducting a hypothesis test: 
- Formulate the Null and Alternative Hypothesis
- Gather evidence(data)
- Calculate the test statistic
- Make a conclusion

## **Using Randomly Generated Data:**

**Problem:**
A telecom company claims that customer pay 400 bob a month on average for internet. We take 50 random bills and find the average is 250 bob permonth. Is the company lying?

Claim: avg = 400
Based on the sample: 
     - n =50
     - sample mean = 250 
     - sample sd = 15


**Step 1: Formulate the Hypotheses:**
- Null (claim): mean = 400
- Alternative: mean != 400

- note: we are dealing with a *two tailed test* and it is numerical in nature hence the ideal test would be a t-test

#### **Import Necessary Libraries**

In [20]:
import numpy as np 
import pandas as pd
from scipy import stats
from sklearn.datasets import load_iris

#### **Generate/ Simulate the data(evidence/ data)**

In [4]:
np.random.seed(42) # it generates pseudo random numbers = > Mathematical formular (consitency or rather enable reproducability), 42 states that i willbe statring from the 42nd position
bills = np.random.normal(250, 15, 50) # mean -250, sd - 15, n - 50

In [5]:
output =f"We have generated {len(bills)} random bills"
print(output)

We have generated 50 random bills

#### **Sample Statistic:**

In [6]:
mean = bills.mean()
sd = bills.std()
n = len(bills)

output = f"MEAN: {mean:.3f} || Standard Deviation: {sd:.3f} || Sample Size: {n}"
print(output)

MEAN: 246.618 || Standard Deviation: 13.864 || Sample Size: 50

In [8]:
t_stat, p_value = stats.ttest_1samp(bills, 400) # 400 is the claimed parameter value/ mean

output = f"Test Statistic: {t_stat:.3f} || p-value: {p_value:.3f}"
print(output)

Test Statistic: -77.442 || p-value: 0.000

#### **Conclusion:**

*Decision Rule:*
- if p< alpha => Reject the Null Hyp. (statistically signifant)
- if p>= alpha => fail to reject the Null Hyp. (not statistically signifant)

In [10]:
# assume the lvele of signifiance(alpha) = 0.05
alpha = 0.05

output =""
if p_value < 0.05:
    output = "Reject the Null Hypothsis"
else:
    output = "Fail to reject the Null Hypothesis"

print(output)

Reject the Null Hypothsis

## **Using Real Grouped data:**

data: Iris Dataset


[Iris Dataset Load](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html)

#### **Load Dataset**

In [26]:
iris_data = load_iris()
df = pd.DataFrame(iris_data.data, columns = iris_data.feature_names)
df['species'] = iris_data.target_names[iris_data.target]
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [30]:
df['petal length (cm)'].describe()

count    150.000000
mean       3.758000
std        1.765298
min        1.000000
25%        1.600000
50%        4.350000
75%        5.100000
max        6.900000
Name: petal length (cm), dtype: float64

In [29]:
df.describe(include='object')

/tmp/ipykernel_8584/87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

       species
count      150
unique       3
top     setosa
freq        50

In [27]:
df['species'].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str